# This file was generated by GoReleaser. DO NOT EDIT.
cask "chippy" do
  version "1.7.0"

  on_macos do
    on_intel do
      sha256 "4e289d46af411f0b6898bcbfb43a1954b07b22957c2b1b144352a00a5bb859c9"
      url "https://github.com/nkane/chippy/releases/download/v#{version}/chippy_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "bf2ac04e8e4034f809746b597f7ab8901101ed4b7a575f1e0a9e22f2f11cc3b2"
      url "https://github.com/nkane/chippy/releases/download/v#{version}/chippy_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9bc63ee2fc07a31ebbbaa854640efcbc8c24606480100a75086b5a2e7d18685e"
      url "https://github.com/nkane/chippy/releases/download/v#{version}/chippy_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "551925e0e665bbf46dcf531d2266155ff287154b9a35536e2befe73b1cbeef6a"
      url "https://github.com/nkane/chippy/releases/download/v#{version}/chippy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "chippy"
  desc "TUI 6502 emulator + ca65/cc65 source-level debugger"
  homepage "https://github.com/nkane/chippy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chippy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chippy"]
    end
  end

  # No zap stanza required

end
