# This file was generated by GoReleaser. DO NOT EDIT.
cask "chippy" do
  version "1.8.0"

  on_macos do
    on_intel do
      sha256 "ffda9042db47034a1f35fec08e7a0acaced31b700c91d1a5cc3e1fde15512dcf"
      url "https://github.com/nkane/chippy/releases/download/v#{version}/chippy_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "21eb9dd8d2443f18ccfb0e828cd9e8a3cb43fbfe38b53cd58a9e566b74bd919e"
      url "https://github.com/nkane/chippy/releases/download/v#{version}/chippy_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a05c3145bed68a24e197c29a3a3925982ab62b3893d8a062b1b816577f26813e"
      url "https://github.com/nkane/chippy/releases/download/v#{version}/chippy_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "cec838cee57b504af2c866a08ce3becb2d63d8795e2157cb5344ba77bdf40495"
      url "https://github.com/nkane/chippy/releases/download/v#{version}/chippy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "chippy"
  desc "TUI 6502 emulator + ca65/cc65 source-level debugger"
  homepage "https://github.com/nkane/chippy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chippy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chippy"]
    end
  end

  # No zap stanza required

end
