# This file was generated by GoReleaser. DO NOT EDIT.
cask "chippy" do
  version "1.9.0"

  on_macos do
    on_intel do
      sha256 "5bb91988ddcef4162eecd7f935e3b291641c2e83fc19b6cae855f08ccbd81877"
      url "https://github.com/nkane/chippy/releases/download/v#{version}/chippy_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e7b1b20469ffb0e144c42d0bd113fdd65a582e9aa0dfa0fb819844ac17420a66"
      url "https://github.com/nkane/chippy/releases/download/v#{version}/chippy_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d3fe12cc90284a504e8a446c973462ca9c46712bb3a1f9aa49374c45a27760b6"
      url "https://github.com/nkane/chippy/releases/download/v#{version}/chippy_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3bdb3517103e8798c6c31d55cdd565d5afc4bb9a853c182dbd36de2669c0f807"
      url "https://github.com/nkane/chippy/releases/download/v#{version}/chippy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "chippy"
  desc "TUI 6502 emulator + ca65/cc65 source-level debugger"
  homepage "https://github.com/nkane/chippy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chippy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chippy"]
    end
  end

  # No zap stanza required

end
