# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chippy < Formula
  desc "TUI 6502 emulator + ca65/cc65 source-level debugger"
  homepage "https://github.com/nkane/chippy"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nkane/chippy/releases/download/v0.4.0/chippy_0.4.0_darwin_x86_64.tar.gz"
      sha256 "4ea531d49c3ea5d6c91a4a3fbbd1a328240c957476f4babe20912cf064b5611e"

      define_method(:install) do
        bin.install "chippy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nkane/chippy/releases/download/v0.4.0/chippy_0.4.0_darwin_arm64.tar.gz"
      sha256 "bd64e056f585b72303f998be579b592781e7523d7bc574cad7e4995f9dec75b5"

      define_method(:install) do
        bin.install "chippy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nkane/chippy/releases/download/v0.4.0/chippy_0.4.0_linux_x86_64.tar.gz"
      sha256 "736aa43b1a19967a81f77c055a526b7f5548aa8adb2250c039da6181d2301a05"
      define_method(:install) do
        bin.install "chippy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nkane/chippy/releases/download/v0.4.0/chippy_0.4.0_linux_arm64.tar.gz"
      sha256 "a12967ac6fe8416dc53ad6cddd3c76c7c6e2d0cca13e6f01f4fa6738ee37ff47"
      define_method(:install) do
        bin.install "chippy"
      end
    end
  end

  test do
    system "#{bin}/chippy", "--help"
  end
end
