# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chippy < Formula
  desc "TUI 6502 emulator + ca65/cc65 source-level debugger"
  homepage "https://github.com/nkane/chippy"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nkane/chippy/releases/download/v0.3.0/chippy_0.3.0_darwin_x86_64.tar.gz"
      sha256 "764074d0119de9eeb2202369dc46a7653957684ad8b3c8b6fa22d580d27dce2b"

      define_method(:install) do
        bin.install "chippy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nkane/chippy/releases/download/v0.3.0/chippy_0.3.0_darwin_arm64.tar.gz"
      sha256 "826b37a86b36eb587a0a434a6851e8302f582ab0fee9591724aee889c76be0ac"

      define_method(:install) do
        bin.install "chippy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nkane/chippy/releases/download/v0.3.0/chippy_0.3.0_linux_x86_64.tar.gz"
      sha256 "bce3fbd2561e0ff1e2b32c3872367792e4e7f73fd65314ac651731fcedcb1499"
      define_method(:install) do
        bin.install "chippy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nkane/chippy/releases/download/v0.3.0/chippy_0.3.0_linux_arm64.tar.gz"
      sha256 "aafa222ee8c97d4672bf07135991626cdb63a160bb4bee4992a054e7c0eeb42c"
      define_method(:install) do
        bin.install "chippy"
      end
    end
  end

  test do
    system "#{bin}/chippy", "--help"
  end
end
